### ISSUE TITLE
Literature Review - Assessing Risk from Satellite Data

### ISSUE THREAD

**Issue by luke-scot** [ai4er-cdt/gtc-exposure#1]
- Especially looking out for any measures of progress
- Insurance vs humanitarian risk assessments/mapping
- Quantifying Risk
- Previous localised similar work - potential for transfer to other areas

**Comment by JoycelynLongdon** [comment]
https://docs.google.com/document/d/11B_VVnp5xfm7o5ypRQZx8ulpkdHCN4kmQVI7LhQ7uGw/edit?usp=sharing
