### ISSUE TITLE
Get something running on JASMIN

### ISSUE THREAD

**Issue by luke-scot** [ai4er-cdt/gtc-exposure#6]
* Trial a jupyter notebook on LOTUS (maybe take an example from Descartes to check compatibility)
* * Record process so others can get an idea

**Comment by Ira-Shokar** [comment]
Please find the videos of the process in here:
https://drive.google.com/drive/folders/1Za3fC1hcDeWijteWrzE27-D5zrjIb0l_?usp=sharing
